### ISSUE TITLE
Small layout changes

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/panicbutton.io#12]
Make all "post-title spaces" height consistent. For instance after the "Full Decription" heading, or the "Goals" heading here: http://panicinitiative.github.io/panicbutton.io/pact-activities/pact-activities-01-introduction.html the spaces are too small, while after "Materials" it's a bit too big.

Also add a little bit more space in between the paragraphs (for instance between the "Welcome and Introduction" and the "World Map" paragraphs).

Also on this page: http://panicinitiative.github.io/panicbutton.io/pact-activities/pact-activities-02-risk-mapping.html add a bit more space after the yellow box (before"Be Careful")

**Comment by jmatsushita** [comment]
Also remove the Up arrow which is not bringing too much :)

**Comment by naturalshine** [comment]
I added and evened out spaces -- let me know if it needs a bit more tweaking!
