### ISSUE TITLE
Remove the Mobile Digital Security section from the Training Kit

### ISSUE THREAD

**Issue by jimmylogan** [PanicInitiative/panicbutton.io#15]
Hi,  

we should remove the Mobile Digital Security Kit from the Training Page [[here](http://panicinitiative.github.io/panicbutton.io/pact/pact.html) (the icon, the explanation and the page that it links to).

We have no content for it at the moment so let's take it out for the time being and we can add it back in at a later date.

**Comment by naturalshine** [comment]
@jimmylogan I removed this from the website, the zip file of cards, and from the pdfs in the media/pdf file, BUT the [yellow counter](https://panicinitiative.github.io/panicbutton.io/pact-app/pact-app-01-app-setup-and-practice.html) at the top of the cards is created with 7 cards in mind; the counter will not be "complete" without a seventh card or a total redesign... thoughts?

**Comment by jmatsushita** [comment]
@jimmylogan ?

**Comment by jimmylogan** [comment]
Hi! I think that this is a small thing that most users either won't notice and even fewer will care about. Rather than redesign, suggest that we leave it as is in readiness for when we do have the mobile digital security kit.  For the time being,  let's think of it as being like [this](http://thepurloinedletter.blogspot.co.uk/2006/07/deliberate-mistake.html?_sm_au_=iVVV0PPHRq0RKJq5) :-)
