### ISSUE TITLE
Increase some text size on the Training Kit page

### ISSUE THREAD

**Issue by jimmylogan** [PanicInitiative/panicbutton.io#17]
Currently the size of the font on the Goals, Methodology and Time Span sections on the [Training Kit page ](http://panicinitiative.github.io/panicbutton.io/pact/pact.html) looks a little small. 

Can we increase it a couple of points?

**Comment by naturalshine** [comment]
@jimmylogan this is changed by this [pull merge](https://github.com/PanicInitiative/panicbutton.io/commit/8a8ec2561c43ccb43ab231906c578a2a53ab9ad9) -- does it look better now?

**Comment by jimmylogan** [comment]
Looks good!
