### ISSUE TITLE
2 boxes of text appearing on the 'About Us' page

### ISSUE THREAD

**Issue by jimmylogan** [PanicInitiative/panicbutton.io#20]
There are two boxes of random text appearing at the bottom of the [About Us](https://panicbutton.io/about.html) page. 

It might have changed when the hyperlink was put in for #18 and am not sure if it needs to be removed or amended.

**Comment by naturalshine** [comment]
@jimmylogan this is fixed & closed by this [pull merge](https://github.com/PanicInitiative/panicbutton.io/commit/8a8ec2561c43ccb43ab231906c578a2a53ab9ad9)

**Comment by jimmylogan** [comment]
Great - thanks!
