### ISSUE TITLE
Fix relative paths

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/panicbutton.io#4]
Some images don't display and some links don't work on http://panicinitiative.github.io/panicbutton.io/

Fix the links so that they work both with a sub path (/panucbutton.io) and a top level path (/).

**Comment by keikreutler** [comment]
Updated base_path and to all absolute links so that they work absolute in local env, and relative in production.

**Comment by jmatsushita** [comment]
In the end given that I want to move away from Jekyll Bootstrap I've used baseurl as explained here (https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/).

This means that the site is locally served with ```jekyll serve``` and from http://0.0.0.0:4000/panicbutton.io/
