### ISSUE TITLE
Work out what's going on with the Download PDF button.

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/panicbutton.io#5]
The original doesn't have a button (anymore): http://the-engine-room.github.io/PACT-kit/pact%20activities/Introduction/

The current merge has a button that doesn't work. http://iilab.github.io/teampanicbutton.github.io/pact-activities/pact-activities-01-introduction.html

Note that the [pdf folder](https://github.com/the-engine-room/PACT-kit/tree/gh-pages/pdf) has not been merged yet (and probably should be).

**Comment by naturalshine** [comment]
The PDF button, on clicking, calls a function [ fromHTMLtoPDF() ] that doesn't exist yet. I suspect this is why it's been removed on the original -- someone didn't get around to writing the functionality. I can add writing a function to do this onto my list if you'd like.

**Comment by jmatsushita** [comment]
Thanks for the analysis! Maybe we can first replace the PDF button to a link to the corresponding PDF in the ```pdf``` folder for now?

**Comment by naturalshine** [comment]
Ah yes, that's the best solution :) Will do

**Comment by naturalshine** [comment]
@jmatsushita This is also fixed, with the button linked to the correct PDF, as we discussed.

**Comment by jmatsushita** [comment]
Oops... I'm getting something weird when opening in the browser:

![image](https://cloud.githubusercontent.com/assets/356097/11873898/1ac2d818-a4dd-11e5-955e-932354dfd516.png)

When opening in Adobe Reader there's further insights about what might be going on:

![image](https://cloud.githubusercontent.com/assets/356097/11873949/675673ba-a4dd-11e5-8f9e-7d712cc75ff9.png)

**Comment by naturalshine** [comment]
Ahh, weird. I think this must have been some glitch; the pdf's are looking fine to me upon regeneration of the site, both from the "download PDF" button, and in the .zip files of the game/ training kit. Of course, upon regeneration of the PDFs with new content, this will need to be checked again.
